import { NextRequest, NextResponse } from 'next/server';
import { cookies } from 'next/headers';
import { createClient, createAdminClient } from '@/lib/supabase/server';
import { applyRateLimit, rateLimiters } from '@/lib/ratelimit';
import type { Role } from '@/types/auth';

interface LineItem {
  description: string;
  quantity: number | string;
  unit_price: number | string;
  item_type?: string;
  item_id?: string;
  display_order?: number;
}

// GET /api/payment/invoices - List all invoices (Admin only)
export async function GET(request: NextRequest) {
  try {
    const cookieStore = await cookies();
    const supabase = await createClient(cookieStore);
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Check user role (CEO or Manager - level <= 2)
    const { data: userData } = await supabase
      .from('users')
      .select('role:roles(*)')
      .eq('id', user.id)
      .single();

    const role = (Array.isArray(userData?.role) ? userData.role[0] : userData?.role) as Role | undefined;
    if (!role || role.level > 2) {
      return NextResponse.json({ error: 'Forbidden - Admin access required' }, { status: 403 });
    }

    const supabaseAdmin = await createAdminClient();
    const { searchParams } = new URL(request.url);
    const status = searchParams.get('status');
    const customerId = searchParams.get('customer_id');

    // Build query
    let query = supabaseAdmin
      .from('invoices')
      .select(`
        *,
        payment_link:payment_links(*),
        transaction:payment_transactions(*),
        line_items:invoice_line_items(*)
      `)
      .order('created_at', { ascending: false });

    // Apply filters
    if (status) {
      query = query.eq('status', status);
    }

    if (customerId) {
      query = query.eq('customer_id', customerId);
    }

    const { data: invoices, error } = await query;

    if (error) {
      console.error('Failed to fetch invoices:', error);
      return NextResponse.json({ error: 'Failed to fetch invoices' }, { status: 500 });
    }

    return NextResponse.json({ invoices });
  } catch (error) {
    console.error('Invoices GET error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

// POST /api/payment/invoices - Create new invoice (Admin only)
export async function POST(request: NextRequest) {
  // Apply rate limiting (10 requests per hour for payment operations)
  const rateLimitResponse = await applyRateLimit(request, rateLimiters.payment);
  if (rateLimitResponse) return rateLimitResponse;

  try {
    const cookieStore = await cookies();
    const supabase = await createClient(cookieStore);
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Check user role
    const { data: userData } = await supabase
      .from('users')
      .select('role:roles(*)')
      .eq('id', user.id)
      .single();

    const role = (Array.isArray(userData?.role) ? userData.role[0] : userData?.role) as Role | undefined;
    if (!role || role.level > 2) {
      return NextResponse.json({ error: 'Forbidden - Admin access required' }, { status: 403 });
    }

    const body = await request.json();
    const {
      customer_name,
      customer_email,
      customer_phone,
      customer_address,
      issue_date,
      due_date,
      tax_rate,
      discount_amount,
      notes,
      line_items,
    } = body;

    // Validation
    if (!customer_name || !customer_email || !line_items || line_items.length === 0) {
      return NextResponse.json(
        { error: 'Missing required fields: customer_name, customer_email, line_items' },
        { status: 400 }
      );
    }

    const supabaseAdmin = await createAdminClient();

    // Calculate totals
    let subtotal = 0;
    const validatedLineItems = line_items.map((item: LineItem, index: number) => {
      const quantity = parseFloat(String(item.quantity)) || 1;
      const unitPrice = parseFloat(String(item.unit_price)) || 0;
      const amount = quantity * unitPrice;
      subtotal += amount;

      return {
        description: item.description,
        quantity,
        unit_price: unitPrice,
        amount,
        item_type: item.item_type || null,
        item_id: item.item_id || null,
        display_order: item.display_order ?? index,
      };
    });

    const taxRateValue = parseFloat(String(tax_rate)) || 0;
    const discountValue = parseFloat(String(discount_amount)) || 0;
    const taxAmount = (subtotal * taxRateValue) / 100;
    const total = subtotal + taxAmount - discountValue;

    // Invoice number is auto-generated by database function
    // Create invoice
    const { data: invoice, error: invoiceError } = await supabaseAdmin
      .from('invoices')
      .insert({
        customer_name,
        customer_email,
        customer_phone: customer_phone || null,
        customer_address: customer_address || null,
        issue_date: issue_date || new Date().toISOString().split('T')[0],
        due_date: due_date || null,
        subtotal,
        tax_rate: taxRateValue,
        tax_amount: taxAmount,
        discount_amount: discountValue,
        total,
        status: 'draft',
        notes: notes || null,
        created_by_id: user.id,
      })
      .select()
      .single();

    if (invoiceError) {
      console.error('Failed to create invoice:', invoiceError);
      return NextResponse.json({ error: 'Failed to create invoice' }, { status: 500 });
    }

    // Create line items
    const lineItemsWithInvoiceId = validatedLineItems.map((item: typeof validatedLineItems[0]) => ({
      ...item,
      invoice_id: invoice.id,
    }));

    const { error: lineItemsError } = await supabaseAdmin
      .from('invoice_line_items')
      .insert(lineItemsWithInvoiceId);

    if (lineItemsError) {
      console.error('Failed to create line items:', lineItemsError);
      // Rollback: delete invoice
      await supabaseAdmin.from('invoices').delete().eq('id', invoice.id);
      return NextResponse.json({ error: 'Failed to create invoice line items' }, { status: 500 });
    }

    // Fetch complete invoice with line items
    const { data: completeInvoice } = await supabaseAdmin
      .from('invoices')
      .select(`
        *,
        line_items:invoice_line_items(*)
      `)
      .eq('id', invoice.id)
      .single();

    return NextResponse.json({ invoice: completeInvoice }, { status: 201 });
  } catch (error) {
    console.error('Invoice creation error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
